containerizationV1

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -61,7 +61,7 @@ jobs:
           export IMAGE_NAME="${{ inputs.image }}"
 
           ssh polydev <<EOF
-            set -e  # Fail fast if any command fails       
+            set -e  # Fail fast if any command fails         
 
             echo "Removing existing repo directory if it exists..."
             rm -rf ~/MyPolyBot
@@ -70,7 +70,7 @@ jobs:
             git clone --branch feature/containerization https://github.com/MajedSaade/MyPolyBot.git ~/MyPolyBot
 
             echo "Changing into repo directory..."
-            cd ~/MyPolyBot || { echo "ERROR: Repo not found after clone"; exit 1; }       
+            cd ~/MyPolyBot || { echo "ERROR: Repo not found after clone"; exit 1; }         
 
             echo "Current directory:"
             pwd
@@ -111,4 +111,4 @@ jobs:
             docker compose -f docker-compose.dev.yaml up -d --remove-orphans
 
             echo "Deployment completed successfully."
-          EOF
+            EOF
