containerizationV1

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -53,12 +53,14 @@ jobs:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
           DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
           DISCORD_DEV_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN_DEV }}
+          REPO_NAME: MyPolyBot
         run: |
           export EC2_HOST="${{ secrets.POLYBOT_EC2_HOST_DEV }}"
           export EC2_USERNAME="${{ secrets.EC2_USERNAME }}"
+          export REPO_NAME="MyPolyBot"
 
-          ssh polydev <<'EOF'
-            cd ~/${REPO_NAME} || { echo "ERROR: Repo not found"; exit 1; }
+          ssh polydev <<EOF
+            cd ~/\$REPO_NAME || { echo "ERROR: Repo not found"; exit 1; }
 
             echo "Current directory:"
             pwd
@@ -74,8 +76,8 @@ jobs:
                 sudo mkdir -p /etc/apt/keyrings
                 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
                 echo \
-                  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-                  $(lsb_release -cs) stable" | \
+                  "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+                  \$(lsb_release -cs) stable" | \
                   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                 sudo apt-get update
                 sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
@@ -92,7 +94,8 @@ jobs:
             STATUS_SERVER_PORT=8443
             " > .env
 
-            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
+            echo \$DOCKERHUB_TOKEN | docker login -u \$DOCKERHUB_USERNAME --password-stdin
+
             docker compose -f docker-compose.dev.yaml pull
             docker compose -f docker-compose.dev.yaml up -d --remove-orphans
            EOF
